# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

env:
  - GITHUB_TOKEN
  - HOMEBREW_TAP_GITHUB_TOKEN
  - COSIGN_EXPERIMENTAL=true

before:
  hooks:
    - go mod download
    - go mod verify
    - bun install --frozen-lockfile
    - bun run build

builds:
  - binary: ory-admin-ui
    env:
      - CGO_ENABLED=0
    flags:
      - "-trimpath"
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
      - "-X main.builtBy=goreleaser"
    main: .

archives:
  - format_overrides:
      - formats:
          - zip
        goos: windows
    formats:
      - tar.gz
    id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dist: .goreleaser-dist

dockers_v2:
  - images:
      - licenseware/{{ .ProjectName }}
      - ghcr.io/licenseware/{{ .ProjectName }}
    dockerfile: Dockerfile.goreleaser
    tags:
      - "{{ if not .IsSnapshot }}v{{ .Version }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}.{{ .Patch }}{{ end }}"
      - "{{ .FullCommit }}"
      - "{{ if .IsNightly }}latest{{ end }}"
    extra_files:
      - ./
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.description": "Ory Admin UI - The admin user interface for Ory services"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.version": "{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: "{{ not .Env.DISABLE_SBOM }}"

docker_signs:
  - id: default
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    cmd: cosign
    output: true

docker_digest:
  name_template: "digest.txt"
  disable: "{{ .Env.NO_DIGEST }}"

report_sizes: true

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

announce:
  skip: "{{gt .Patch 0}}"

checksum:
  algorithm: sha256
  name_template: checksums.txt

homebrew_casks:
  - commit_msg_template: Brew formula update for {{ .ProjectName }} version {{ .Tag }}
    description: The admin user interface for Ory services
    homepage: https://github.com/licenseware/ory-admin-ui
    license: Apache-2.0
    name: ory-admin-ui
    repository:
      name: homebrew-tap
      owner: licenseware
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ory-admin-ui"]
          end
          puts "✨ ory-admin-ui installed successfully!"
          puts ""
          puts "📝 Tip: You can enable shell completion by running:"
          puts "   ory-admin-ui completion bash  # for bash"
          puts "   ory-admin-ui completion zsh   # for zsh"
          puts "   ory-admin-ui completion fish  # for fish"
          puts ""
          puts "📚 For more information and usage instructions, visit:"
          puts "   https://github.com/licenseware/ory-admin-ui"
